FilePath :
  author: 'resources/Author.csv'
  conference: 'resources/Conference.csv'
  journal: 'resources/Journal.csv'
  paper: 'resources/Paper.csv'
  paperAuthor: 'resources/PaperAuthor.csv'
  train: 'resources/train.csv'
  test: 'test.csv'
  outputFiles_xgb: 'output/MG21370009_xgb.csv'
  outputFiles_ran: 'output/MG21370009_ran.csv'
  test2: 'test2.csv'
  conference_feature: 'feature/Conference.pkl'
  journal_feature: 'feature/Journal.pkl'
  paper_feature: 'feature/Paper.pkl'
  author_feature: 'feature/Author.pkl'
  save_models_xgb: 'save_models/dmcd_xgb.pickle.dat'
  save_models_ran: 'save_models/dmcd_ran.pickle.dat'
